### ISSUE TITLE
No winner popup 

### ISSUE THREAD

**Issue by tekraj** [sumn2u/baghchal#10]
Even after tigers eats 5 goats there is no winner popup.
Due to which player gets confused and plays untill tiger eats all 20 goats.
We should show winner popup after tiger eats 5 goats.

**Comment by sumn2u** [comment]
FIx on this commit [9c2235c13cc827ce009c0be2f5397da049997f19](https://github.com/sumn2u/baghchal/commit/9c2235c13cc827ce009c0be2f5397da049997f19)

**Comment by sumn2u** [comment]
Feel free to re-open this pull request if this still exists.
