### ISSUE TITLE
great effort but, cannot handle multiplayer mode, also the rules for victory aren't set properly.

### ISSUE THREAD

**Issue by Dimanjan** [sumn2u/baghchal#13]

**Comment by sumn2u** [comment]
@Dimanjan   Thanks for checking it. We have fixed the issue related and also added the missing rules. i.e "A tiger or goat cannot move a piece in such a way that a similar position appears repeatedly on the board."

Regarding multiplayer, we are working on it.

**Comment by chaurasiyasakshi** [comment]
How can I download this same code run on my pc??? It's not working

**Comment by sumn2u** [comment]
> How can I download this same code run on my pc??? It's not working

You can download the compiled version from [here](https://iamsuman.itch.io/bagchal).

**Comment by chaurasiyasakshi** [comment]
I want code.....as this is my project topic.



-----------***-----------
*Thanks & Regards,*
Sakshi Chaurasiya
